package view.form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import view.controller.MainFormController;

/**
 *
 * @author Dragon
 */
public class MainForm extends javax.swing.JFrame {

//    private TableModelEmployee tme;
    private MainFormController mainFormController;

    /**
     * Creates new form MainForm
     *
     * @param mainFormController
     */
    public MainForm(MainFormController mainFormController) {
        initComponents();
        this.mainFormController = mainFormController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServerStatus = new javax.swing.JLabel();
        lblServerStatusText = new javax.swing.JLabel();
        btnStartServer = new javax.swing.JButton();
        btnStopServer = new javax.swing.JButton();
        lblAuthenticatedEmployees = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        menuBarMain = new javax.swing.JMenuBar();
        menuConfiguration = new javax.swing.JMenu();
        menuItemServerConfiguration = new javax.swing.JMenuItem();
        menuItemDatabaseConfiguration = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        lblServerStatus.setText("Server status:");

        lblServerStatusText.setText("Server is stopped!");

        btnStartServer.setText("Start server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        btnStopServer.setText("Stop server");
        btnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopServerActionPerformed(evt);
            }
        });

        lblAuthenticatedEmployees.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAuthenticatedEmployees.setText("Authenticated employees:");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmployees);

        menuConfiguration.setText("Configuration");

        menuItemServerConfiguration.setText("Server configuration");
        menuItemServerConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemServerConfigurationActionPerformed(evt);
            }
        });
        menuConfiguration.add(menuItemServerConfiguration);

        menuItemDatabaseConfiguration.setText("Database configuration");
        menuItemDatabaseConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDatabaseConfigurationActionPerformed(evt);
            }
        });
        menuConfiguration.add(menuItemDatabaseConfiguration);

        menuBarMain.add(menuConfiguration);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartServer)
                    .addComponent(lblServerStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServerStatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopServer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAuthenticatedEmployees)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServerStatus)
                    .addComponent(lblServerStatusText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartServer)
                    .addComponent(btnStopServer))
                .addGap(56, 56, 56)
                .addComponent(lblAuthenticatedEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        try {
            mainFormController.startServer();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Start server error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopServerActionPerformed
        try {
            mainFormController.stopServer();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Stop server error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStopServerActionPerformed

    private void menuItemServerConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemServerConfigurationActionPerformed
        mainFormController.openPortConfigurationForm();
    }//GEN-LAST:event_menuItemServerConfigurationActionPerformed

    private void menuItemDatabaseConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDatabaseConfigurationActionPerformed
        mainFormController.openDatabaseConfigurationForm();
    }//GEN-LAST:event_menuItemDatabaseConfigurationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthenticatedEmployees;
    private javax.swing.JLabel lblServerStatus;
    private javax.swing.JLabel lblServerStatusText;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuConfiguration;
    private javax.swing.JMenuItem menuItemDatabaseConfiguration;
    private javax.swing.JMenuItem menuItemServerConfiguration;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnStartServer() {
        return btnStartServer;
    }

    public JButton getBtnStopServer() {
        return btnStopServer;
    }

    public JMenu getMenuConfiguration() {
        return menuConfiguration;
    }

    public void setTableEmployeesModel(TableModel tableModel) {
        tblEmployees.setModel(tableModel);
    }
}
