
package domain;

import java.io.Serializable;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Dragon
 */
public interface GeneralDObject extends Serializable{
    
    String getTableName();
    GeneralDObject getNewRecord(ResultSet rs) throws SQLException;
    String getInsertionColumns();
    String getAtrPlaceHolders();
    void setPreparedStatementParameters(PreparedStatement ps) throws SQLException;
    String getPKWhereCondition();
    String getFKWhereCondition();
    String getAttributeValuesWhereCondition();
    String getUpdateColumnsWithPlaceHolders();
    String getJoinCondition();
    void setAutoGeneratedKey(long id);
}
