package communication.util;

/**
 *
 * @author Dragon
 */
public enum Operation {
    LOGIN,
    LOGOUT,
    ADD_SERVICE,
    GET_ALL_SERVICES,
    DELETE_SERVICE,
    GET_SERVICES_BY_CONDITION,
    ADD_EMPLOYEE,
    GET_ALL_EMPLOYEES,
    GET_EMPLOYEES_BY_CONDITION,
    EDIT_EMPLOYEE,
    DELETE_EMPLOYEE,
    ADD_SERVICE_BOOK,
    GET_ALL_SERVICE_BOOKS,
    GET_SERVICE_BOOKS_BY_CONDITION,
    DELETE_SERVICE_BOOK,
    EDIT_SERVICE_BOOK,
    GET_REPAIRS_BY_FK_CONDITION,
    GET_REPAIR_ITEMS_BY_FK_CONDITION,
    ADD_REPAIR,
    DELETE_REPAIR,
    EDIT_REPAIR
}
